-- BD-22: Advisor observations as persistent records with resolve-to-initiative flow.
-- Each observation is generated by the synthesis LLM call and persisted here so it can be
-- individually resolved into an initiative. status=open (default) or resolved.
-- resolved_initiative_id is set when the human resolves the observation via the creation form.

CREATE TABLE IF NOT EXISTS observations (
    id                      TEXT        PRIMARY KEY,
    project_id              TEXT        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    content                 TEXT        NOT NULL,
    status                  TEXT        NOT NULL DEFAULT 'open'
                                        CHECK (status IN ('open', 'resolved')),
    resolved_initiative_id  TEXT        REFERENCES initiatives(id) ON DELETE SET NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS observations_project_id_idx ON observations(project_id);
CREATE INDEX IF NOT EXISTS observations_status_idx     ON observations(project_id, status);
